const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../app/src/main/assets/core.js');
function fixture(){let s=C.empty();s.opening={cash:100000,debit:1000000};s.income=2000000;s.debts=[{id:'d',name:'Equipo',originalAmount:300000,balance:300000,payment:100000,totalPayments:3,startDate:C.month()+'-01',dueDay:31,paidPayments:[],paidMonths:[],balanceMode:'total',active:true}];s.fixedExpenses=[{id:'f',name:'Internet',amount:50000,active:true,dueDay:5}];C.ensureBudget(s);return s;}
test('payment updates balance and pending but preserves budget and DTI',()=>{const s=fixture(),before=C.metrics(s),key=C.obligations(s).find(i=>i.kind==='debt').key;C.pay(s,key,{amount:100000,date:C.today(),method:'debit'});const after=C.metrics(s);assert.equal(after.debit,before.debit-100000);assert.equal(after.pending,before.pending-100000);assert.equal(after.budgetFree,before.budgetFree);assert.equal(after.dti,before.dti);assert.equal(after.consumption,0);assert.equal(after.outflow,100000);assert.equal(after.debit-after.pending,before.debit-before.pending);});
test('double payment rejected without any further changes',()=>{const s=fixture(),key=C.obligations(s)[0].key;C.pay(s,key,{amount:100000});const saved=JSON.stringify(s);assert.throws(()=>C.pay(s,key,{amount:100000}));assert.equal(JSON.stringify(s),saved);});
test('partial payments accumulate and reversal reopens obligation',()=>{const s=fixture(),key=C.obligations(s)[0].key;C.pay(s,key,{amount:40000});assert.equal(C.obligations(s)[0].remaining,60000);assert.equal(s.debts[0].paidPayments.length,0);const t=C.pay(s,key,{amount:60000});assert.equal(C.obligations(s)[0].paid,true);C.reverseTransaction(s,t.id);assert.equal(C.obligations(s)[0].remaining,60000);assert.equal(s.debts[0].balance,260000);assert.equal(C.balances(s).debit,960000);});
test('fixed payment is one expense and one debit',()=>{const s=fixture(),key=C.obligations(s).find(i=>i.kind==='fixed').key;const t=C.pay(s,key,{amount:50000});assert.equal(C.metrics(s).consumption,50000);assert.equal(C.metrics(s).fixed,50000);C.reverseTransaction(s,t.id);assert.equal(C.metrics(s).consumption,0);assert.equal(C.balances(s).debit,1000000);});
test('negative funds stay visible instead of being clipped',()=>{const s=fixture();C.record(s,{kind:'expense',amount:1200000,date:C.today(),name:'Expense',method:'debit'});assert.equal(C.balances(s).debit,-200000);});
test('transfer is neither expense nor income',()=>{const s=fixture();C.record(s,{kind:'transfer',amount:30000,date:C.today(),name:'Retiro',method:'debit',to:'cash'});assert.equal(C.metrics(s).liquidity,1100000);assert.equal(C.metrics(s).outflow,0);assert.equal(C.balances(s).cash,130000);});
test('month ends use actual calendar including leap year',()=>{assert.equal(C.dueDate('2028-02',31),'2028-02-29');assert.equal(C.dueDate('2027-02',31),'2027-02-28');assert.equal(C.dueDate('2026-04',31),'2026-04-30');assert.equal(C.validDate('2026-02-31'),false);});
test('principal-only payment separates debt reduction from cash outflow',()=>{const s=fixture();s.debts[0].balanceMode='principal';C.pay(s,C.obligations(s)[0].key,{amount:100000,principal:80000});assert.equal(s.debts[0].balance,220000);assert.equal(C.balances(s).debit,900000);});
test('fully paid debt stays in current budget, no future unpaid commitments',()=>{const s=fixture();s.debts[0].balance=100000;C.pay(s,C.obligations(s)[0].key,{amount:100000});assert.equal(C.metrics(s).debt,100000);assert.equal(C.metrics(s,C.addMonth(C.month(),1)).debt,0);});
test('legacy import preserves opening balances and historical data exactly',()=>{const raw={balances:{cash:12.34,debit:456.78},income:1000,accounts:[],categories:[],fixedExpenses:[],debts:[{id:'d',name:'Old',balance:100,payment:50,originalAmount:200,totalPayments:4,startDate:'2026-07-01',paidPayments:[1,2],type:'loan'}],expenses:[{id:'e',name:'Old expense',amount:25,date:'2026-08-01',method:'Débito',categoryId:''}],liquidityHistory:[{date:'2026-08-01',value:400}]};const s=C.migrate(raw);assert.deepEqual(C.balances(s),{cash:1234,debit:45678});assert.equal(s.transactions[0].amount,2500);assert.deepEqual(s.debts[0].paidPayments,[1,2]);assert.equal(s.liquidityHistory[0].value,40000);assert.deepEqual(C.migrate(s),s);});
test('invalid import rejects missing collections, malformed numbers and duplicate ids',()=>{assert.throws(()=>C.migrate({}));const s=fixture();s.debts.push(C.clone(s.debts[0]));assert.throws(()=>C.validate(s));});
test('editing fixed commitments preserves a paid month record',()=>{const s=fixture();C.pay(s,C.obligations(s).find(i=>i.kind==='fixed').key,{amount:50000});s.fixedExpenses[0].amount=75000;C.refreshBudget(s);assert.equal(C.metrics(s).fixed,50000);assert.equal(C.metrics(s,C.addMonth(C.month(),1)).fixed,75000);});
