/* Run: NODE_PATH=... node tests/ui.test.cjs. Requires Playwright + local Chromium.
   OSP_CHROME and OSP_URL can override the executable and test server. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.OSP_CHROME||'/tmp/osp-chrome/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',()=>{throw Error('Unexpected native browser dialog');});await page.goto(process.env.OSP_URL||'http://127.0.0.1:8765');await page.getByRole('button',{name:'Empezar desde cero',exact:true}).click();await page.getByRole('heading',{name:'Cada grano cuenta.'}).waitFor();
await page.getByRole('button',{name:'Ajustes',exact:true}).click();await page.getByRole('button',{name:'Ajustar saldos',exact:true}).click();await page.locator('[name=debit]').fill('10000');await page.locator('[name=cash]').fill('1000');await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('button',{name:'Ingreso previsto',exact:true}).click();await page.locator('[name=income]').fill('20000');await page.getByRole('button',{name:'Guardar',exact:true}).click();
await page.locator('nav [data-id=debt]').click();await page.getByRole('button',{name:'Agregar deuda',exact:true}).click();await page.locator('[name=name]').fill('Equipo de trabajo');await page.locator('[name=originalAmount]').fill('3000');await page.locator('[name=balance]').fill('3000');await page.locator('[name=payment]').fill('1000');await page.locator('[name=totalPayments]').fill('3');await page.locator('[name=financingCost]').fill('0');await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('heading',{name:'Equipo de trabajo',exact:true}).waitFor();
const before=await page.evaluate(()=>OSP.metrics(state));await page.getByRole('button',{name:'Pagar deuda',exact:true}).click();await page.getByRole('button',{name:'Registrar pago',exact:true}).click();const after=await page.evaluate(()=>OSP.metrics(state));assert.equal(after.debit,before.debit-100000);assert.equal(after.budgetFree,before.budgetFree);await page.locator('#toast [data-action=undo]').click();const restored=await page.evaluate(()=>OSP.metrics(state));assert.equal(restored.debit,before.debit);await page.reload();await page.getByRole('heading',{name:'Cada grano cuenta.'}).waitFor();assert.equal(await page.evaluate(()=>OSP.metrics(state).debit),before.debit);
await page.locator('nav [data-id=expense]').click();await page.getByRole('button',{name:'Fijos y suscripciones',exact:true}).click();await page.getByRole('button',{name:'Agregar gasto fijo',exact:true}).click();await page.locator('[name=name]').fill('Internet');await page.locator('[name=amount]').fill('500');await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('button',{name:'Pagar gasto fijo',exact:true}).click();await page.locator('[name=amount]').fill('200');await page.getByRole('button',{name:'Registrar pago',exact:true}).click();assert.equal(await page.evaluate(()=>OSP.obligations(state).find(i=>i.kind==='fixed').remaining),30000);
await page.locator('nav [data-id=goal]').click();await page.getByRole('button',{name:'Crear meta',exact:true}).click();await page.locator('[name=name]').fill('Una escapada');await page.locator('[name=target]').fill('5000');await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('button',{name:'Aportar o liberar reserva',exact:true}).click();await page.locator('[name=amount]').fill('1000');await page.getByRole('button',{name:'Guardar',exact:true}).click();assert.equal(await page.evaluate(()=>OSP.metrics(state).reserved),100000);
await page.locator('nav [data-id=expense]').click();await page.getByRole('button',{name:'Movimientos',exact:true}).click();await page.getByRole('button',{name:'Mostrar filtros',exact:true}).click();await page.locator('#filters [name=kind]').selectOption('fixed');assert.equal(await page.locator('.item-title').count(),1);await page.locator('#search').fill('no existe');assert.equal(await page.locator('.item-title').count(),0);
await page.getByRole('button',{name:'Ajustes',exact:true}).click();await page.getByRole('button',{name:'Importar respaldo',exact:true}).click();await page.locator('#importFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"no":"data"}')});assert.equal(await page.evaluate(()=>state.debts.length),1);
// A write failure must leave the in-memory state untouched.
await page.evaluate(()=>{window.originalWrite=writeStore;writeStore=async()=>{throw Error('Simulated storage failure')};});const count=await page.evaluate(()=>state.categories.length);await page.getByRole('button',{name:'Agregar categoría',exact:true}).click();await page.locator('[name=name]').fill('No guardar');await page.getByRole('button',{name:'Guardar',exact:true}).click();assert.equal(await page.evaluate(()=>state.categories.length),count);assert.match(await page.locator('.form-error').innerText(),/Simulated/);await page.evaluate(()=>{writeStore=window.originalWrite;closeModal();});
// Reference screenshots contain fabricated demo data only.
await page.evaluate(async()=>{await commit('Datos de muestra',s=>{s.transactions.push({id:'demo1',kind:'expense',name:'Despensa',amount:85000,date:OSP.today(),method:'debit',categoryId:s.categories[0].id});s.transactions.push({id:'demo2',kind:'expense',name:'Transporte',amount:24000,date:OSP.today(),method:'debit',categoryId:s.categories[1].id});s.liquidityHistory=[{date:OSP.month()+'-01',value:950000},{date:OSP.month()+'-03',value:1020000},{date:OSP.month()+'-05',value:970000},{date:OSP.month()+'-07',value:1100000}];});tab='home';render();document.querySelector('#toast').classList.remove('visible');});
fs.mkdirSync('build/previews',{recursive:true});await page.screenshot({path:'build/previews/Melange-inicio.png',fullPage:true});await page.locator('nav [data-id=goal]').click();await page.screenshot({path:'build/previews/Melange-metas.png',fullPage:true});
for(const width of [360,390,430]){await page.setViewportSize({width,height:844});for(const name of ['home','expense','debt','calendar','goal']){await page.locator(`nav [data-id=${name}]`).click();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${name} overflow at ${width}`);}}
assert.deepEqual(errors,[]);await browser.close();console.log('UI checks passed: onboarding, balances, debt payment + undo + reload, partial fixed payment, goals, filters, invalid import, write failure rollback, 3 mobile widths.');})().catch(e=>{console.error(e);process.exit(1)});
